name: Execute build and tests

on:
    # run at the event pushed by Jenkins
    repository_dispatch:

    # run at the event pushed by Jenkins
    push:
        branches: [ master ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Check out from repository
              uses: actions/checkout@v2
            - name: Checkout submodules
              run: git submodule update --init --recursive --remote
  
            # Install prerequisites
            - name:  Install prerequisites
              run:   sudo ./conf/scripts/_setup.sh
              shell: sh

            # Build
            - name: Build
              run:   sudo ./_wcc.sh
              shell: sh
