name: Execute build and tests

on:
    # run at the event pushed by Jenkins
    repository_dispatch:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses:  actions/checkout@v2
            - run:   /bin/sh _setup.sh
            - run:   /bin/sh _wcc.sh
