# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install wget
      - name: Install wget
        run: choco install wget --no-progress

      # Download latest Open Watcom
      - name: Download latest Open Watcom
        run: |
          wget https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/open-watcom-2_0-c-win-x64.exe
          #setup.exe  -s p -ns
          #dir

      # Install OpenWatcom
      - name: Install OpenWatcom
        run: open-watcom-2_0-c-win-x64.exe -s -p -ns
        shell: cmd

      # Download Regina REXX
      - name: Download Regine REXX
        run: wget https://sourceforge.net/projects/regina-rexx/files/regina-rexx/3.9.4/Regina394w64.exe

