name: Doxygen
on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: mattnotmitt/doxygen-action@v1.9.2
        with:
          doxyfile-path: 'OS2/CMD'
